In [16]:
import pandas as pd
import numpy as np

In [17]:
s = pd.read_csv("C:\\Users\\Lenovo\\OneDrive\\Desktop\\Deep Learning\\RNN\\100_Unique_QA_Dataset.csv")


In [18]:
s.head()

question      answer
0                   What is the capital of France?       Paris
1                  What is the capital of Germany?      Berlin
2               Who wrote 'To Kill a Mockingbird'?  Harper-Lee
3  What is the largest planet in our solar system?     Jupiter
4   What is the boiling point of water in Celsius?         100

In [19]:
s.shape

(90, 2)

## Tokenize

In [20]:
def tokenize(text):
    text = text.lower()
    text = text.replace('?','')
    text = text.replace("'", "")
    return text.split()

In [21]:
tokenize('What is the capital of France?')

['what', 'is', 'the', 'capital', 'of', 'france']

In [22]:
# vocab
vocab = {'<UNK>':0}

In [23]:
def build_vocab(row):
    print(row['question'],row['answer'])

In [24]:
s.apply(build_vocab,axis = 1)

What is the capital of France? Paris
What is the capital of Germany? Berlin
Who wrote 'To Kill a Mockingbird'? Harper-Lee
What is the largest planet in our solar system? Jupiter
What is the boiling point of water in Celsius? 100
Who painted the Mona Lisa? Leonardo-da-Vinci
What is the square root of 64? 8
What is the chemical symbol for gold? Au
Which year did World War II end? 1945
What is the longest river in the world? Nile
What is the capital of Japan? Tokyo
Who developed the theory of relativity? Albert-Einstein
What is the freezing point of water in Fahrenheit? 32
Which planet is known as the Red Planet? Mars
Who is the author of '1984'? George-Orwell
What is the currency of the United Kingdom? Pound
What is the capital of India? Delhi
Who discovered gravity? Newton
How many continents are there on Earth? 7
Which gas do plants use for photosynthesis? CO2
What is the smallest prime number? 2
Who invented the telephone? Alexander-Graham-Bell
What is the capital of Australia? Canber

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [25]:
def build_vocab(row):
    tokenized_question =tokenize(row['question'])
    tokenized_answer = tokenize(row['answer'])
    print(tokenized_question,tokenized_answer)

In [26]:
s.apply(build_vocab,axis =1)

['what', 'is', 'the', 'capital', 'of', 'france'] ['paris']
['what', 'is', 'the', 'capital', 'of', 'germany'] ['berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird'] ['harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system'] ['jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius'] ['100']
['who', 'painted', 'the', 'mona', 'lisa'] ['leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64'] ['8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold'] ['au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end'] ['1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world'] ['nile']
['what', 'is', 'the', 'capital', 'of', 'japan'] ['tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity'] ['albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit'] ['32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet'] ['mars']
['who', 'is', 'the', 'auth

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [27]:
def build_vocab(row):
    tokenized_question =tokenize(row['question'])
    tokenized_answer = tokenize(row['answer'])
    merge_tokens = tokenized_question + tokenized_answer
    print(merge_tokens)

In [28]:
s.apply(build_vocab,axis = 1)

['what', 'is', 'the', 'capital', 'of', 'france', 'paris']
['what', 'is', 'the', 'capital', 'of', 'germany', 'berlin']
['who', 'wrote', 'to', 'kill', 'a', 'mockingbird', 'harper-lee']
['what', 'is', 'the', 'largest', 'planet', 'in', 'our', 'solar', 'system', 'jupiter']
['what', 'is', 'the', 'boiling', 'point', 'of', 'water', 'in', 'celsius', '100']
['who', 'painted', 'the', 'mona', 'lisa', 'leonardo-da-vinci']
['what', 'is', 'the', 'square', 'root', 'of', '64', '8']
['what', 'is', 'the', 'chemical', 'symbol', 'for', 'gold', 'au']
['which', 'year', 'did', 'world', 'war', 'ii', 'end', '1945']
['what', 'is', 'the', 'longest', 'river', 'in', 'the', 'world', 'nile']
['what', 'is', 'the', 'capital', 'of', 'japan', 'tokyo']
['who', 'developed', 'the', 'theory', 'of', 'relativity', 'albert-einstein']
['what', 'is', 'the', 'freezing', 'point', 'of', 'water', 'in', 'fahrenheit', '32']
['which', 'planet', 'is', 'known', 'as', 'the', 'red', 'planet', 'mars']
['who', 'is', 'the', 'author', 'of', '19

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [29]:
def build_vocab(row):
    tokenized_question = tokenize(row['question'])
    tokenized_answer = tokenize(row['answer'])
    merge_tokens = tokenized_question + tokenized_answer
    for token in merge_tokens:
        if token not in vocab:
            vocab[token] = len(vocab)

In [30]:
s.apply(build_vocab,axis = 1)

0     None
1     None
2     None
3     None
4     None
      ... 
85    None
86    None
87    None
88    None
89    None
Length: 90, dtype: object

In [31]:
vocab

{'<UNK>': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'who': 10,
 'wrote': 11,
 'to': 12,
 'kill': 13,
 'a': 14,
 'mockingbird': 15,
 'harper-lee': 16,
 'largest': 17,
 'planet': 18,
 'in': 19,
 'our': 20,
 'solar': 21,
 'system': 22,
 'jupiter': 23,
 'boiling': 24,
 'point': 25,
 'water': 26,
 'celsius': 27,
 '100': 28,
 'painted': 29,
 'mona': 30,
 'lisa': 31,
 'leonardo-da-vinci': 32,
 'square': 33,
 'root': 34,
 '64': 35,
 '8': 36,
 'chemical': 37,
 'symbol': 38,
 'for': 39,
 'gold': 40,
 'au': 41,
 'which': 42,
 'year': 43,
 'did': 44,
 'world': 45,
 'war': 46,
 'ii': 47,
 'end': 48,
 '1945': 49,
 'longest': 50,
 'river': 51,
 'nile': 52,
 'japan': 53,
 'tokyo': 54,
 'developed': 55,
 'theory': 56,
 'relativity': 57,
 'albert-einstein': 58,
 'freezing': 59,
 'fahrenheit': 60,
 '32': 61,
 'known': 62,
 'as': 63,
 'red': 64,
 'mars': 65,
 'author': 66,
 '1984': 67,
 'george-orwell': 68,
 'currency': 69,
 'unit

# Convert words to Numerical indices

In [32]:
def text_to_indices(text, vocab):
    indexed_text = []  # Initialize the list to hold the indices
    for token in tokenize(text):  # Assuming tokenize() splits the text into tokens
        if token in vocab:
            indexed_text.append(vocab[token])  # Append the index of the token from vocab
        else:                           
            indexed_text.append(vocab['<UNK>'])  # Append index for unknown tokens
    return indexed_text


In [33]:
text_to_indices("what is campus", vocab)

[1, 2, 0]

In [34]:
import torch
from torch.utils.data import Dataset, DataLoader

In [35]:
class QADataset(Dataset):
    def __init__(self,s,vocab):
        self.s = s
        self.vocab = vocab
    def __len__(self):
        return self.s.shape[0]
    def __getitem__(self,index):
        numerical_question = text_to_indices(self.s.iloc[index]['question'],self.vocab)
        numerical_answer = text_to_indices(self.s.iloc[index]['answer'], self.vocab)
        return torch.tensor(numerical_question), torch.tensor(numerical_answer)

In [36]:
dataset = QADataset(s,vocab)

In [37]:
dataset[10]

(tensor([ 1,  2,  3,  4,  5, 53]), tensor([54]))

In [38]:
dataloader = DataLoader(dataset,batch_size =1,shuffle=True)

In [39]:
for question, answer in dataloader:
    print(question, answer)

tensor([[ 78,  79, 261, 151,  14, 262, 153]]) tensor([[36]])
tensor([[1, 2, 3, 4, 5, 8]]) tensor([[9]])
tensor([[  1,   2,   3, 122, 123,  19,   3,  45]]) tensor([[124]])
tensor([[10, 55,  3, 56,  5, 57]]) tensor([[58]])
tensor([[  1,   2,   3,  37, 133,   5,  26]]) tensor([[134]])
tensor([[10, 75, 76]]) tensor([[77]])
tensor([[  1,   2,   3, 212,   5,  14, 213, 214]]) tensor([[215]])
tensor([[ 78,  79, 195,  81,  19,   3, 196, 197, 198]]) tensor([[199]])
tensor([[42, 86, 87, 88, 89, 39, 90]]) tensor([[91]])
tensor([[78, 79, 80, 81, 82, 83, 84]]) tensor([[85]])
tensor([[  1,   2,   3, 103,   5, 104,  19, 105]]) tensor([[106]])
tensor([[ 1,  2,  3, 59, 25,  5, 26, 19, 60]]) tensor([[61]])
tensor([[ 1,  2,  3, 69,  5, 53]]) tensor([[260]])
tensor([[1, 2, 3, 4, 5, 6]]) tensor([[7]])
tensor([[ 42, 117, 118,   3, 119,  94, 120]]) tensor([[121]])
tensor([[ 42, 174,   2,  62,  39, 175, 176,  12, 177, 178]]) tensor([[179]])
tensor([[  1,   2,   3,  92, 137,  19,   3,  45]]) tensor([[185]])
ten

In [40]:
import torch.nn as nn


In [41]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init_()
        self.embedding = nn.Embedding(vocab_size, embedding_dim = 50)
        self.rnn = nn.RNN(50,64)
        self.fc = nn.Linear(64,vocab_size)
    def forward(self):
        pass


In [42]:
dataset[0][0]

tensor([1, 2, 3, 4, 5, 6])

In [43]:
x = nn.Embedding(324, embedding_dim=50)

In [44]:
a= x(dataset[0][0])

In [45]:
a.shape

torch.Size([6, 50])

In [46]:
a

tensor([[-6.1833e-01, -1.1170e+00,  5.1767e-01, -1.5383e+00,  1.0005e+00,
         -4.2858e-01, -9.9231e-01, -9.6172e-01, -8.4433e-01,  6.5579e-01,
          8.1390e-01, -6.9606e-01,  1.1026e+00,  8.1413e-01,  2.7011e-01,
         -4.8685e-01,  1.7733e+00, -8.4496e-02,  6.2465e-01,  2.0423e-01,
         -1.6315e+00, -1.4993e+00,  2.3353e-01,  6.2691e-01,  4.2534e-01,
          2.6960e-01,  3.2549e-01,  2.3054e-01,  2.6680e-01,  6.1313e-03,
          5.9163e-01, -4.1707e-01,  4.5404e-03, -2.5233e-01, -1.3228e+00,
         -1.0651e-02, -8.7815e-02,  2.7172e-01, -1.7722e+00,  1.8870e+00,
          8.0641e-01, -7.1650e-01,  7.1049e-01,  1.1506e+00,  1.0867e+00,
         -7.2686e-01, -1.9305e+00, -9.8923e-01,  1.0940e+00, -1.7952e-02],
        [ 1.2846e+00,  2.9012e-01, -6.3106e-01,  5.8330e-01, -6.2452e-01,
         -1.6767e+00,  9.5702e-01,  5.2430e-01, -9.2684e-01, -1.8426e+00,
          1.3264e+00, -2.9998e-01, -4.6919e-01, -2.9637e-01, -3.1309e-01,
         -2.7289e-01, -5.8824e-01, -8

In [47]:
y = nn.RNN(50, 64)

In [48]:
y(a)

(tensor([[ 9.5154e-01, -8.1253e-01,  4.7961e-01, -3.9553e-01,  4.3450e-01,
           6.0807e-01, -5.4048e-01,  4.4466e-02, -6.8848e-01,  7.0940e-01,
           1.7245e-01, -6.6904e-01, -1.0924e-01, -4.5532e-01,  5.3105e-01,
           6.9517e-01,  8.5001e-01,  1.0301e-01,  9.3038e-03, -3.5580e-01,
          -2.1593e-01, -3.6277e-01, -1.0226e-01,  7.7279e-01, -2.5268e-01,
           3.5101e-01, -5.1669e-01,  2.0220e-01, -2.8011e-01,  3.9746e-01,
           3.2006e-02,  9.1867e-02,  1.4095e-01,  3.8492e-01, -2.8977e-01,
           6.7471e-01,  1.0634e-01, -3.2426e-01, -2.7843e-01,  4.7480e-01,
          -3.2695e-01, -2.4871e-01,  6.9683e-01, -3.8063e-01, -1.6154e-01,
          -3.2326e-01, -1.1660e-01,  6.5028e-01, -6.5389e-02, -1.0436e-01,
           8.3157e-01, -2.9258e-01, -2.5403e-01, -6.9085e-02,  8.2393e-02,
           1.8684e-01, -2.5019e-01,  8.1364e-02,  2.8573e-02,  2.7748e-01,
           1.6973e-01, -2.2118e-01,  3.0429e-01,  4.5155e-01],
         [-4.1956e-01,  2.1453e-01,  

In [49]:
y(a)[0].shape

torch.Size([6, 64])

In [50]:
y(a)[1].shape

torch.Size([1, 64])

In [51]:
b = y(a)[1]

In [52]:
z = nn.Linear(64, 324)

In [53]:
z(b)

tensor([[ 0.2052, -0.1455,  0.1638, -0.0133,  0.0981,  0.0259,  0.0522,  0.1711,
         -0.0106, -0.2091,  0.2101,  0.0675,  0.1206,  0.1219, -0.4490,  0.3261,
          0.0786,  0.2257,  0.0058,  0.3043, -0.2789,  0.2326,  0.4892,  0.1542,
         -0.3761, -0.3266,  0.3313,  0.0300, -0.3474,  0.2813, -0.0066, -0.2051,
          0.0834,  0.3263,  0.2266, -0.1112, -0.1066,  0.1209,  0.1014, -0.1051,
         -0.0203,  0.1400, -0.0453,  0.2297,  0.3249,  0.0804,  0.1707, -0.0580,
          0.1312,  0.2165, -0.0855, -0.3389,  0.1973, -0.3779,  0.2006,  0.1864,
          0.5404, -0.0207, -0.5332,  0.0525, -0.1684,  0.0136, -0.5946,  0.2151,
          0.5137, -0.1968, -0.1171, -0.1600, -0.0683,  0.1860, -0.1112,  0.0508,
          0.4815,  0.4075,  0.2942, -0.2614,  0.0084, -0.1190,  0.0583,  0.4337,
         -0.3256,  0.0472, -0.2740,  0.1413,  0.0064,  0.2316,  0.2348,  0.0714,
          0.3914, -0.2839,  0.1058, -0.0274, -0.2113, -0.1589, -0.1475, -0.2991,
          0.3876, -0.3157,  

In [54]:
z(b).shape

torch.Size([1, 324])

In [55]:
class SimpleRNN(nn.Module):
    def __init__(self, vocab_size):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim = 50)
        self.rnn = nn.RNN(50,64, batch_first = True)
        self.fc = nn.Linear(64,vocab_size)
    def forward(self, question):
        embedded_question = self.embedding(question)
        hidden, final = self.rnn(embedded_question)
        output = self.fc(final.squeeze(0))
        return output

In [56]:
learning_rate = 0.001
epochs = 50

In [57]:
model = SimpleRNN(len(vocab))

In [58]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr = learning_rate)

In [59]:
# training loop

for epoch in range(epochs):
    total_loss = 0
    correct = 0
    total = 0

    for question, answer in dataloader:
        optimizer.zero_grad()
        # forward pass
        output = model(question)
        # loss calculation
        loss = criterion(output, answer[0])  
        # gradients
        loss.backward()
        # update
        optimizer.step()
        total_loss += loss.item()

        # Calculate accuracy
        predicted = torch.argmax(output, dim=1)  # Get the index of the highest probability
        if predicted.item() == answer[0].item():
            correct += 1
        total += 1

    print(f"Epoch: {epoch+1}, Loss: {total_loss:.4f}")


Epoch: 1, Loss: 524.7996
Epoch: 2, Loss: 456.6656
Epoch: 3, Loss: 378.0373
Epoch: 4, Loss: 316.9381
Epoch: 5, Loss: 266.7683
Epoch: 6, Loss: 219.1716
Epoch: 7, Loss: 174.6392
Epoch: 8, Loss: 135.9777
Epoch: 9, Loss: 104.7241
Epoch: 10, Loss: 79.8385
Epoch: 11, Loss: 61.1985
Epoch: 12, Loss: 47.3499
Epoch: 13, Loss: 37.2820
Epoch: 14, Loss: 29.5850
Epoch: 15, Loss: 24.1715
Epoch: 16, Loss: 20.1306
Epoch: 17, Loss: 16.7297
Epoch: 18, Loss: 14.2197
Epoch: 19, Loss: 12.1865
Epoch: 20, Loss: 10.4895
Epoch: 21, Loss: 9.1591
Epoch: 22, Loss: 8.0676
Epoch: 23, Loss: 7.1514
Epoch: 24, Loss: 6.3927
Epoch: 25, Loss: 5.7152
Epoch: 26, Loss: 5.1711
Epoch: 27, Loss: 4.6784
Epoch: 28, Loss: 4.2397
Epoch: 29, Loss: 3.8754
Epoch: 30, Loss: 3.5522
Epoch: 31, Loss: 3.2586
Epoch: 32, Loss: 2.9988
Epoch: 33, Loss: 2.7754
Epoch: 34, Loss: 2.5659
Epoch: 35, Loss: 2.3802
Epoch: 36, Loss: 2.2071
Epoch: 37, Loss: 2.0561
Epoch: 38, Loss: 1.9164
Epoch: 39, Loss: 1.7925
Epoch: 40, Loss: 1.6724
Epoch: 41, Loss: 1.5

In [60]:
def predict(model, question, threshold = 0.5):
    # convert question to numbers
    numerical_question =  text_to_indices(question,vocab)
    # tensor
    question_tensor = torch.tensor(numerical_question).unsqueeze(0)
    # sent to model
    output = model(question_tensor)
    # convert logits to probabilits
    probs = torch.nn.functional.softmax(output, dim =1)
    # find index of max prob
    value, index = torch.max(probs, dim = 1)
    print(value,index)
    if value<threshold:
        print("I dont know")
    else:
        
        print(list(vocab.keys())[index])

In [61]:
predict(model, "what is the capital of japan")

tensor([0.9808], grad_fn=<MaxBackward0>) tensor([54])
tokyo
